try
{
    console.log('start of try');
    getout;
    console.log('End of try');
}
catch(error)
{
    console.log(error.message);
}